image: docker.io/jangorecki/r-pkg
services:
- postgres

variables:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: r_db
  POSTGRES_USER: r_user
  POSTGRES_PASSWORD: r_password

pages:
  script:
    # non-R dependencies
    - apt-get update -qq
    - apt-get -qq install -y libpq-dev
    # install deps
    - Rscript -e 'install.packages(c("RPostgreSQL","data.table","logR"), repos = "https://cran.rstudio.com","https://jangorecki.gitlab.io/logR")'
    # install suggests
    - Rscript -e 'install.packages("microbenchmarkCore", repos = "https://olafmersmann.github.io/drat")'
    # build pkg
    - R CMD build .
    # run check
    - R CMD check $(ls -1t *.tar.gz | head -n 1) --no-manual --as-cran
    # produce artifacts
    - Rscript -e 'drat::insertArtifacts(repodir="public", repo.url="https://jangorecki.gitlab.io/pg", repo.cran=TRUE)'
  artifacts:
    paths:
      - public
